// Generated by CoffeeScript 1.6.3
(function() {
  var https;

  https = require('https');

  exports.getJson = function(url, callback) {
    return https.get(url, function(res) {
      var body;
      body = "";
      res.on('data', function(d) {
        return body = body + d;
      });
      return res.on('end', function() {
        var json;
        console.log('follower body ->' + body);
        json = JSON.parse(body);
        return callback(json);
      });
    });
  };

  exports.postJson = function(host, path, token, json, callback) {
    var headers, jsonString, options, req;
    jsonString = JSON.stringify(json);
    headers = {
      'Content-Type': 'text/html;chartset=utf-8',
      'Content-Length': jsonString.length,
      'encoding': "utf-8"
    };
    options = {
      host: host,
      port: 443,
      path: path + token,
      method: "POST"
    };
    req = https.request(options, function(res) {
      console.log("res status :" + res.statusCode);
      res.on('data', function(chunk) {
        return console.log("CreateMenuRes:" + chunk);
      });
      if (typeof callback === "function") {
        return callback(res);
      }
    });
    console.log("jsonString:->" + jsonString);
    req.write(jsonString);
    return req.end();
  };

}).call(this);
