// Generated by CoffeeScript 1.6.3
(function() {
  var getFollowersUrl, https, next_openidUrl, util;

  https = require('https');

  util = require('util');

  getFollowersUrl = "https://api.weixin.qq.com/cgi-bin/user/get?access_token=%s";

  next_openidUrl = "&next_openid=%s";

  exports.getFollowers = function(access_token, next_openid, callback) {
    var nextUrl, url;
    if (next_openid) {
      nextUrl = util.format(next_openidUrl, next_openid);
    }
    url = util.format(getFollowersUrl, access_token) + nextUrl;
    return https.get(url, function(res) {
      var body;
      body = "";
      res.on('data', function(d) {
        return body = body + d;
      });
      return res.on('end', function() {
        var json;
        console.log('followers body ->' + body);
        json = JSON.parse(body);
        return callback(json);
      });
    });
  };

}).call(this);
